[main]
	registryAddr  = "http://registry.test.com"
	
[alarm]
	enable        = false
	NS            = "alarm.monitor.loda"
	alarmAddr     = ""

[ping]
	enable        = false
	ipList        = ["10.50.","10.90."]

[api]
	enable        = false
	NS            = ["api.loda"]

[log]
	logdir        = "/tmp/alarm-adapter/log"
	loglevel      = "DEBUG"
	logrotatenum  = 5
	logrotatesize = 1887436800