[main]
	registryAddr  = "http://registry.test.com"
	kapacitorAddr = ["http://kapacitor.test.com:9002"]


[log]
	logdir = "/tmp/alarm-adapter/log"
	loglevel = "DEBUG"
	logrotatenum = 5
	logrotatesize = 1887436800