[main]
	alarmNS       = "alarm.monitor.loda"
	registryAddr  = "http://registry.test.com"
	alarmAddr     = ""


[log]
	logdir = "/tmp/alarm-adapter/log"
	loglevel = "DEBUG"
	logrotatenum = 5
	logrotatesize = 1887436800